export type Source = "camera" | "phone";
export type Span = "tall" | "wide" | "square";

export type ArchivePhoto = {
  id: string;
  frame: string;
  source: Source;
  type: string;
  /** Finer grouping within a type, e.g. a product brand within "Product Photography". */
  subtype?: string;
  caption: string;
  path: string;
  tone: "amber" | "rust" | "graphite" | "paper";
  /** Shown in the home page's curated "best of" gallery. */
  featured?: boolean;
  /** Grid span, only used by the home gallery's masonry layout. */
  span?: Span;
};

// Generated from every image currently in public/photos — grouped by its
// folder (source + type). Regenerate by re-running the same scan whenever
// files are added or removed on disk.
export const archivePhotos: ArchivePhoto[] = [
  // --- Camera ---
  {
    id: "p3-8",
    frame: "203P-08",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_1777.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_1777.JPG",
    tone: "amber",
    featured: true,
    span: "wide",
  },
  {
    id: "c1-2",
    frame: "101C-02",
    source: "camera",
    type: "Landscape Photography",
    caption: "DSC_3883.jpg",
    path: "/photos/camera/DSC_3883.jpg",
    tone: "graphite",
  },
  {
    id: "c1-3",
    frame: "101C-03",
    source: "camera",
    type: "Landscape Photography",
    caption: "DSC_3884.jpg",
    path: "/photos/camera/DSC_3884.jpg",
    tone: "paper",
  },
  {
    id: "c1-1",
    frame: "101C-01",
    source: "camera",
    type: "Landscape Photography",
    caption: "DSC_3882.jpg",
    path: "/photos/camera/DSC_3882.jpg",
    tone: "rust",
    featured: true,
    span: "tall",
  },
  {
    id: "c2-1",
    frame: "102C-01",
    source: "camera",
    type: "Portrait Photography",
    caption: "DSC_3767.jpg",
    path: "/photos/camera/Portrait%20Photography/DSC_3767.jpg",
    tone: "rust",
    featured: true,
  },
  {
    id: "c2-2",
    frame: "102C-02",
    source: "camera",
    type: "Portrait Photography",
    caption: "DSC_3768.jpg",
    path: "/photos/camera/Portrait%20Photography/DSC_3768.jpg",
    tone: "graphite",
  },
  {
    id: "c2-3",
    frame: "102C-03",
    source: "camera",
    type: "Portrait Photography",
    caption: "DSC_3769.jpg",
    path: "/photos/camera/Portrait%20Photography/DSC_3769.jpg",
    tone: "paper",
  },
  {
    id: "c2-5",
    frame: "102C-05",
    source: "camera",
    type: "Portrait Photography",
    caption: "DSC_3771.jpg",
    path: "/photos/camera/Portrait%20Photography/DSC_3771.jpg",
    tone: "rust",
  },
  {
    id: "c2-6",
    frame: "102C-06",
    source: "camera",
    type: "Portrait Photography",
    caption: "DSC_3772.jpg",
    path: "/photos/camera/Portrait%20Photography/DSC_3772.jpg",
    tone: "graphite",
  },
  {
    id: "c2-7",
    frame: "102C-07",
    source: "camera",
    type: "Portrait Photography",
    caption: "DSC_3773.jpg",
    path: "/photos/camera/Portrait%20Photography/DSC_3773.jpg",
    tone: "paper",
  },
  {
    id: "c3-1",
    frame: "103C-01",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption:
      "@2aSea Breeze Tea Box with Glass Lid – 6 Adjustable Compartments.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%402aSea%20Breeze%20Tea%20Box%20with%20Glass%20Lid%20%E2%80%93%206%20Adjustable%20Compartments.webp",
    tone: "rust",
  },
  {
    id: "c3-2",
    frame: "103C-02",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption:
      "@2bSea Breeze Tea Box with Glass Lid – 6 Adjustable Compartments.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%402bSea%20Breeze%20Tea%20Box%20with%20Glass%20Lid%20%E2%80%93%206%20Adjustable%20Compartments.webp",
    tone: "graphite",
  },
  {
    id: "c3-3",
    frame: "103C-03",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@3aSea Life Wooden Tissue Box – Summer Coastal Design.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%403aSea%20Life%20Wooden%20Tissue%20Box%20%E2%80%93%20Summer%20Coastal%20Design.webp",
    tone: "paper",
  },
  {
    id: "c3-4",
    frame: "103C-04",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@3bSea Life Wooden Tissue Box – Summer Coastal Design.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%403bSea%20Life%20Wooden%20Tissue%20Box%20%E2%80%93%20Summer%20Coastal%20Design.webp",
    tone: "amber",
  },
  {
    id: "c3-5",
    frame: "103C-05",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@4AMarine Relax Wooden Tissue Box – Coastal Modern Design.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%404AMarine%20Relax%20Wooden%20Tissue%20Box%20%E2%80%93%20Coastal%20Modern%20Design.webp",
    tone: "rust",
  },
  {
    id: "c3-6",
    frame: "103C-06",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@4BMarine Relax Wooden Tissue Box – Coastal Modern Design.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%404BMarine%20Relax%20Wooden%20Tissue%20Box%20%E2%80%93%20Coastal%20Modern%20Design.webp",
    tone: "graphite",
  },
  {
    id: "c3-7",
    frame: "103C-07",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption:
      "@5a Vintage Rose Cutlery Organizer – Classic Design with Storage Drawer.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%405a%20Vintage%20Rose%20Cutlery%20Organizer%20%E2%80%93%20Classic%20Design%20with%20Storage%20Drawer.webp",
    tone: "paper",
  },
  {
    id: "c3-8",
    frame: "103C-08",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption:
      "@5b Vintage Rose Cutlery Organizer – Classic Design with Storage Drawer.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%405b%20Vintage%20Rose%20Cutlery%20Organizer%20%E2%80%93%20Classic%20Design%20with%20Storage%20Drawer.webp",
    tone: "amber",
  },
  {
    id: "c3-9",
    frame: "103C-09",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@6aDecorative Wooden Lantern – MDF.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%406aDecorative%20Wooden%20Lantern%20%E2%80%93%20MDF.webp",
    tone: "rust",
  },
  {
    id: "c3-10",
    frame: "103C-10",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@6bDecorative Wooden Lantern – MDF.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%406bDecorative%20Wooden%20Lantern%20%E2%80%93%20MDF.webp",
    tone: "graphite",
  },
  {
    id: "c3-11",
    frame: "103C-11",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@7aSmall Decorative Wooden Lantern – MDF.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%407aSmall%20Decorative%20Wooden%20Lantern%20%E2%80%93%20MDF.webp",
    tone: "paper",
  },
  {
    id: "c3-12",
    frame: "103C-12",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@7b Small Decorative Wooden Lantern – MDF.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%407b%20Small%20Decorative%20Wooden%20Lantern%20%E2%80%93%20MDF.webp",
    tone: "amber",
  },
  {
    id: "c3-13",
    frame: "103C-13",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@8aSmall Decorative Wooden Lantern – Pink Natural.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%408aSmall%20Decorative%20Wooden%20Lantern%20%E2%80%93%20Pink%20Natural.webp",
    tone: "rust",
  },
  {
    id: "c3-14",
    frame: "103C-14",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@8b Small Decorative Wooden Lantern – Pink Natural.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%408b%20Small%20Decorative%20Wooden%20Lantern%20%E2%80%93%20Pink%20Natural.webp",
    tone: "graphite",
  },
  {
    id: "c3-15",
    frame: "103C-15",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@10a Small Decorative Wooden Lantern – Petrol Blue.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4010a%20Small%20Decorative%20Wooden%20Lantern%20%E2%80%93%20Petrol%20Blue.webp",
    tone: "paper",
  },
  {
    id: "c3-16",
    frame: "103C-16",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@10b Small Decorative Wooden Lantern – Petrol Blue.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4010b%20Small%20Decorative%20Wooden%20Lantern%20%E2%80%93%20Petrol%20Blue.webp",
    tone: "amber",
  },
  {
    id: "c3-17",
    frame: "103C-17",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@11aSmall Decorative Wooden Lantern – Dark Blue.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4011aSmall%20Decorative%20Wooden%20Lantern%20%E2%80%93%20Dark%20Blue.webp",
    tone: "rust",
  },
  {
    id: "c3-18",
    frame: "103C-18",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@11bSmall Decorative Wooden Lantern – Dark Blue.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4011bSmall%20Decorative%20Wooden%20Lantern%20%E2%80%93%20Dark%20Blue.webp",
    tone: "graphite",
  },
  {
    id: "c3-19",
    frame: "103C-19",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption:
      "@12aSmall Decorative Wooden Lantern – Burgundy & Off-White Floral.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4012aSmall%20Decorative%20Wooden%20Lantern%20%E2%80%93%20Burgundy%20%26%20Off-White%20Floral.webp",
    tone: "paper",
  },
  {
    id: "c3-20",
    frame: "103C-20",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption:
      "@12bSmall Decorative Wooden Lantern – Burgundy & Off-White Floral.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4012bSmall%20Decorative%20Wooden%20Lantern%20%E2%80%93%20Burgundy%20%26%20Off-White%20Floral.webp",
    tone: "amber",
  },
  {
    id: "c3-21",
    frame: "103C-21",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@13aMulti-Purpose Wooden Bottle Organizer.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4013aMulti-Purpose%20Wooden%20Bottle%20Organizer.webp",
    tone: "rust",
  },
  {
    id: "c3-22",
    frame: "103C-22",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@13bMulti-Purpose Wooden Bottle Organizer.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4013bMulti-Purpose%20Wooden%20Bottle%20Organizer.webp",
    tone: "graphite",
  },
  {
    id: "c3-23",
    frame: "103C-23",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption:
      "@14aDecorative Wooden Tissue Box with Remote & Mobile Organizer.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4014aDecorative%20Wooden%20Tissue%20Box%20with%20Remote%20%26%20Mobile%20Organizer.webp",
    tone: "paper",
  },
  {
    id: "c3-24",
    frame: "103C-24",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption:
      "@14bDecorative Wooden Tissue Box with Remote & Mobile Organizer.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4014bDecorative%20Wooden%20Tissue%20Box%20with%20Remote%20%26%20Mobile%20Organizer.webp",
    tone: "amber",
  },
  {
    id: "c3-25",
    frame: "103C-25",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@15aRoyal Carved Jewelry Box.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4015aRoyal%20Carved%20Jewelry%20Box.webp",
    tone: "rust",
    featured: true,
    span: "square",
  },
  {
    id: "c3-26",
    frame: "103C-26",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@15bRoyal Carved Jewelry Box.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4015bRoyal%20Carved%20Jewelry%20Box.webp",
    tone: "graphite",
  },
  {
    id: "c3-27",
    frame: "103C-27",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@15cRoyal Carved Jewelry Box.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4015cRoyal%20Carved%20Jewelry%20Box.webp",
    tone: "paper",
  },
  {
    id: "c3-28",
    frame: "103C-28",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@15dRoyal Carved Jewelry Box.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4015dRoyal%20Carved%20Jewelry%20Box.webp",
    tone: "amber",
  },
  {
    id: "c3-29",
    frame: "103C-29",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@16aWinnie Joy Organizer – 2 Compartments.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4016aWinnie%20Joy%20Organizer%20%E2%80%93%202%20Compartments.webp",
    tone: "rust",
  },
  {
    id: "c3-30",
    frame: "103C-30",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@16bWinnie Joy Organizer – 2 Compartments.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4016bWinnie%20Joy%20Organizer%20%E2%80%93%202%20Compartments.webp",
    tone: "graphite",
  },
  {
    id: "c3-31",
    frame: "103C-31",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption:
      "@17aBloom Heart Organizer – 2 Compartments with Heart Handle.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4017aBloom%20Heart%20Organizer%20%E2%80%93%202%20Compartments%20with%20Heart%20Handle.webp",
    tone: "paper",
  },
  {
    id: "c3-32",
    frame: "103C-32",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption:
      "@17bBloom Heart Organizer – 2 Compartments with Heart Handle.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4017bBloom%20Heart%20Organizer%20%E2%80%93%202%20Compartments%20with%20Heart%20Handle.webp",
    tone: "amber",
  },
  {
    id: "c3-33",
    frame: "103C-33",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@18aMasha’Allah Wooden Key Holder – Blessing Home Design.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4018aMasha%E2%80%99Allah%20Wooden%20Key%20Holder%20%E2%80%93%20Blessing%20Home%20Design.webp",
    tone: "rust",
  },
  {
    id: "c3-34",
    frame: "103C-34",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@18bMasha’Allah Wooden Key Holder – Blessing Home Design.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4018bMasha%E2%80%99Allah%20Wooden%20Key%20Holder%20%E2%80%93%20Blessing%20Home%20Design.webp",
    tone: "graphite",
  },
  {
    id: "c3-35",
    frame: "103C-35",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@19aWelcome Rectangular Wooden Key Holder.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4019aWelcome%20Rectangular%20Wooden%20Key%20Holder.webp",
    tone: "paper",
  },
  {
    id: "c3-36",
    frame: "103C-36",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@19bWelcome Rectangular Wooden Key Holder.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4019bWelcome%20Rectangular%20Wooden%20Key%20Holder.webp",
    tone: "amber",
  },
  {
    id: "c3-37",
    frame: "103C-37",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@21aGamer MDF Phone Stand.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4021aGamer%20MDF%20Phone%20Stand.webp",
    tone: "rust",
  },
  {
    id: "c3-38",
    frame: "103C-38",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@21bGamer MDF Phone Stand.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4021bGamer%20MDF%20Phone%20Stand.webp",
    tone: "graphite",
  },
  {
    id: "c3-39",
    frame: "103C-39",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@21cGamer MDF Phone Stand.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4021cGamer%20MDF%20Phone%20Stand.webp",
    tone: "paper",
  },
  {
    id: "c3-40",
    frame: "103C-40",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@21dGamer MDF Phone Stand.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4021dGamer%20MDF%20Phone%20Stand.webp",
    tone: "amber",
  },
  {
    id: "c3-41",
    frame: "103C-41",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@22aClassic Arabesque Wooden Tray – Cutwork Design.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4022aClassic%20Arabesque%20Wooden%20Tray%20%E2%80%93%20Cutwork%20Design.webp",
    tone: "rust",
  },
  {
    id: "c3-42",
    frame: "103C-42",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@22bClassic Arabesque Wooden Tray – Cutwork Design.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4022bClassic%20Arabesque%20Wooden%20Tray%20%E2%80%93%20Cutwork%20Design.webp",
    tone: "graphite",
  },
  {
    id: "c3-43",
    frame: "103C-43",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@23aNautical Ship Wheel Wall Art Set – Double Face.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4023aNautical%20Ship%20Wheel%20Wall%20Art%20Set%20%E2%80%93%20Double%20Face.webp",
    tone: "paper",
  },
  {
    id: "c3-44",
    frame: "103C-44",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@23bNautical Ship Wheel Wall Art Set – Double Face.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4023bNautical%20Ship%20Wheel%20Wall%20Art%20Set%20%E2%80%93%20Double%20Face.webp",
    tone: "amber",
  },
  {
    id: "c3-45",
    frame: "103C-45",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@24aWELCOME Centerpiece Tray – MDF Wood.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4024aWELCOME%20Centerpiece%20Tray%20%E2%80%93%20MDF%20Wood.webp",
    tone: "rust",
  },
  {
    id: "c3-46",
    frame: "103C-46",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@24bWELCOME Centerpiece Tray – MDF Wood.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4024bWELCOME%20Centerpiece%20Tray%20%E2%80%93%20MDF%20Wood.webp",
    tone: "graphite",
  },
  {
    id: "c3-47",
    frame: "103C-47",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@25aRound Carved Wooden Wall Frame.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4025aRound%20Carved%20Wooden%20Wall%20Frame.webp",
    tone: "paper",
  },
  {
    id: "c3-48",
    frame: "103C-48",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@25bRound Carved Wooden Wall Frame.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4025bRound%20Carved%20Wooden%20Wall%20Frame.webp",
    tone: "amber",
  },
  {
    id: "c3-49",
    frame: "103C-49",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@26aDouble-Face Coastal Wall Art.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4026aDouble-Face%20Coastal%20Wall%20Art.webp",
    tone: "rust",
  },
  {
    id: "c3-50",
    frame: "103C-50",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@26bDouble-Face Coastal Wall Art.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4026bDouble-Face%20Coastal%20Wall%20Art.webp",
    tone: "graphite",
  },
  {
    id: "c3-51",
    frame: "103C-51",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@28aGolden Nights Wooden Lantern.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4028aGolden%20Nights%20Wooden%20Lantern.webp",
    tone: "paper",
  },
  {
    id: "c3-52",
    frame: "103C-52",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@28cGolden Nights Wooden Lantern.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4028cGolden%20Nights%20Wooden%20Lantern.webp",
    tone: "amber",
  },
  {
    id: "c3-53",
    frame: "103C-53",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@29aFloral Beige & Dusty Rose.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4029aFloral%20Beige%20%26%20Dusty%20Rose.webp",
    tone: "rust",
  },
  {
    id: "c3-54",
    frame: "103C-54",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@29bFloral Beige & Dusty Rose.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4029bFloral%20Beige%20%26%20Dusty%20Rose.webp",
    tone: "graphite",
  },
  {
    id: "c3-55",
    frame: "103C-55",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@30aOriental Spirit Wooden Lantern.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4030aOriental%20Spirit%20Wooden%20Lantern.webp",
    tone: "paper",
  },
  {
    id: "c3-56",
    frame: "103C-56",
    source: "camera",
    type: "Product Photography",
    subtype: "Handmade-by-dalia-brand",
    caption: "@30bOriental Spirit Wooden Lantern.webp",
    path: "/photos/camera/Product%20Photography/Handmade-by-dalia-brand/%4030bOriental%20Spirit%20Wooden%20Lantern.webp",
    tone: "amber",
  },
  {
    id: "p3-22",
    frame: "203P-22",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_3720.jpeg",
    path: "/photos/mobile/Landscape%20Photography/IMG_3720.jpeg",
    tone: "graphite",
    featured: true,
  },
  {
    id: "c4-2",
    frame: "104C-02",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@1B Leather Passport Cover & Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%401B%20Leather%20Passport%20Cover%20%26%20Luggage%20Tag.webp",
    tone: "graphite",
  },
  {
    id: "c4-3",
    frame: "104C-03",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@1C Leather Passport Cover & Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%401C%20Leather%20Passport%20Cover%20%26%20Luggage%20Tag.webp",
    tone: "paper",
  },
  {
    id: "c4-4",
    frame: "104C-04",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@1D Leather Passport Cover & Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%401D%20Leather%20Passport%20Cover%20%26%20Luggage%20Tag.webp",
    tone: "amber",
  },
  {
    id: "c4-5",
    frame: "104C-05",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@1E Leather Passport Cover & Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%401E%20Leather%20Passport%20Cover%20%26%20Luggage%20Tag.webp",
    tone: "rust",
  },
  {
    id: "c4-6",
    frame: "104C-06",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@1FLeather Passport Cover & Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%401FLeather%20Passport%20Cover%20%26%20Luggage%20Tag.webp",
    tone: "graphite",
  },
  {
    id: "c4-7",
    frame: "104C-07",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@1G Leather Passport Cover & Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%401G%20Leather%20Passport%20Cover%20%26%20Luggage%20Tag.webp",
    tone: "paper",
  },
  {
    id: "c4-8",
    frame: "104C-08",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@1H  Leather Passport Cover & Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%401H%20%20Leather%20Passport%20Cover%20%26%20Luggage%20Tag.webp",
    tone: "amber",
  },
  {
    id: "c4-9",
    frame: "104C-09",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@1I  Leather Passport Cover & Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%401I%20%20Leather%20Passport%20Cover%20%26%20Luggage%20Tag.webp",
    tone: "rust",
  },
  {
    id: "c4-10",
    frame: "104C-10",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@1J  Leather Passport Cover & Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%401J%20%20Leather%20Passport%20Cover%20%26%20Luggage%20Tag.webp",
    tone: "graphite",
  },
  {
    id: "c4-11",
    frame: "104C-11",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@1K Leather Passport Cover & Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%401K%20Leather%20Passport%20Cover%20%26%20Luggage%20Tag.webp",
    tone: "paper",
  },
  {
    id: "c4-12",
    frame: "104C-12",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@1L  Leather Passport Cover & Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%401L%20%20Leather%20Passport%20Cover%20%26%20Luggage%20Tag.webp",
    tone: "amber",
  },
  {
    id: "c4-13",
    frame: "104C-13",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@1M Leather Passport Cover & Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%401M%20Leather%20Passport%20Cover%20%26%20Luggage%20Tag.webp",
    tone: "rust",
  },
  {
    id: "c4-14",
    frame: "104C-14",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@1N Leather Passport Cover & Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%401N%20Leather%20Passport%20Cover%20%26%20Luggage%20Tag.webp",
    tone: "graphite",
  },
  {
    id: "c4-15",
    frame: "104C-15",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@1O Leather Passport Cover & Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%401O%20Leather%20Passport%20Cover%20%26%20Luggage%20Tag.webp",
    tone: "paper",
  },
  {
    id: "c4-16",
    frame: "104C-16",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@1P Leather Passport Cover & Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%401P%20Leather%20Passport%20Cover%20%26%20Luggage%20Tag.webp",
    tone: "amber",
  },
  {
    id: "c4-17",
    frame: "104C-17",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@1Q Leather Passport Cover & Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%401Q%20Leather%20Passport%20Cover%20%26%20Luggage%20Tag.webp",
    tone: "rust",
  },
  {
    id: "c4-18",
    frame: "104C-18",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@1R Leather Passport Cover & Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%401R%20Leather%20Passport%20Cover%20%26%20Luggage%20Tag.webp",
    tone: "graphite",
  },
  {
    id: "c4-19",
    frame: "104C-19",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@2A Leather Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%402A%20Leather%20Luggage%20Tag.webp",
    tone: "paper",
  },
  {
    id: "c4-20",
    frame: "104C-20",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@2B Leather Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%402B%20Leather%20Luggage%20Tag.webp",
    tone: "amber",
  },
  {
    id: "c4-21",
    frame: "104C-21",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@2C Leather Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%402C%20Leather%20Luggage%20Tag.webp",
    tone: "rust",
  },
  {
    id: "c4-22",
    frame: "104C-22",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@2D Leather Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%402D%20Leather%20Luggage%20Tag.webp",
    tone: "graphite",
  },
  {
    id: "c4-23",
    frame: "104C-23",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@2E Leather Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%402E%20Leather%20Luggage%20Tag.webp",
    tone: "paper",
  },
  {
    id: "c4-24",
    frame: "104C-24",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@2F Leather Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%402F%20Leather%20Luggage%20Tag.webp",
    tone: "amber",
  },
  {
    id: "c4-25",
    frame: "104C-25",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@2G Leather Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%402G%20Leather%20Luggage%20Tag.webp",
    tone: "rust",
  },
  {
    id: "c4-26",
    frame: "104C-26",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@2H Leather Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%402H%20Leather%20Luggage%20Tag.webp",
    tone: "graphite",
  },
  {
    id: "c4-27",
    frame: "104C-27",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@2I Leather Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%402I%20Leather%20Luggage%20Tag.webp",
    tone: "paper",
  },
  {
    id: "c4-28",
    frame: "104C-28",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@2J Leather Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%402J%20Leather%20Luggage%20Tag.webp",
    tone: "amber",
  },
  {
    id: "c4-29",
    frame: "104C-29",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@2K Leather Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%402K%20Leather%20Luggage%20Tag.webp",
    tone: "rust",
  },
  {
    id: "c4-30",
    frame: "104C-30",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@2L Leather Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%402L%20Leather%20Luggage%20Tag.webp",
    tone: "graphite",
  },
  {
    id: "c4-31",
    frame: "104C-31",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@2M Leather Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%402M%20Leather%20Luggage%20Tag.webp",
    tone: "paper",
  },
  {
    id: "c4-32",
    frame: "104C-32",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@2N Leather Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%402N%20Leather%20Luggage%20Tag.webp",
    tone: "amber",
  },
  {
    id: "c4-33",
    frame: "104C-33",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@2O Leather Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%402O%20Leather%20Luggage%20Tag.webp",
    tone: "rust",
  },
  {
    id: "c4-34",
    frame: "104C-34",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@2P Leather Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%402P%20Leather%20Luggage%20Tag.webp",
    tone: "graphite",
  },
  {
    id: "c4-35",
    frame: "104C-35",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@2Q Leather Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%402Q%20Leather%20Luggage%20Tag.webp",
    tone: "paper",
  },
  {
    id: "c4-36",
    frame: "104C-36",
    source: "camera",
    type: "Product Photography",
    subtype: "Hudzo-brand",
    caption: "@2R Leather Luggage Tag.webp",
    path: "/photos/camera/Product%20Photography/Hudzo-brand/%402R%20Leather%20Luggage%20Tag.webp",
    tone: "amber",
  },

  // --- Phone ---
  {
    id: "p1-1",
    frame: "201P-01",
    source: "phone",
    type: "Animal Photography",
    caption: "IMG_1163.jpeg",
    path: "/photos/mobile/IMG_1163.jpeg",
    tone: "rust",
  },
  {
    id: "p1-2",
    frame: "201P-02",
    source: "phone",
    type: "Animal Photography",
    caption: "IMG_1200.jpeg",
    path: "/photos/mobile/IMG_1200.jpeg",
    tone: "graphite",
  },
  {
    id: "p1-3",
    frame: "201P-03",
    source: "phone",
    type: "Animal Photography",
    caption: "IMG_2436.jpeg",
    path: "/photos/mobile/IMG_2436.jpeg",
    tone: "paper",
  },
  {
    id: "p1-4",
    frame: "201P-04",
    source: "phone",
    type: "Animal Photography",
    caption: "IMG_E0925.JPG",
    path: "/photos/mobile/IMG_E0925.JPG",
    tone: "amber",
  },
  {
    id: "p1-5",
    frame: "201P-05",
    source: "phone",
    type: "Animal Photography",
    caption: "IMG_E0932.JPG",
    path: "/photos/mobile/IMG_E0932.JPG",
    tone: "rust",
    featured: true,
  },
  {
    id: "p2-1",
    frame: "202P-01",
    source: "phone",
    type: "Architecture Photography",
    caption: "IMG_0272.JPG",
    path: "/photos/mobile/Architecture%20Photography/IMG_0272.JPG",
    tone: "rust",
  },
  {
    id: "p2-2",
    frame: "202P-02",
    source: "phone",
    type: "Architecture Photography",
    caption: "IMG_1566.jpeg",
    path: "/photos/mobile/Architecture%20Photography/IMG_1566.jpeg",
    tone: "graphite",
    featured: true,
  },
  {
    id: "p2-3",
    frame: "202P-03",
    source: "phone",
    type: "Architecture Photography",
    caption: "IMG_1604.jpeg",
    path: "/photos/mobile/Architecture%20Photography/IMG_1604.jpeg",
    tone: "paper",
  },
  {
    id: "p2-4",
    frame: "202P-04",
    source: "phone",
    type: "Architecture Photography",
    caption: "IMG_1607.jpeg",
    path: "/photos/mobile/Architecture%20Photography/IMG_1607.jpeg",
    tone: "amber",
    featured: true,
    span: "tall",
  },
  {
    id: "p2-5",
    frame: "202P-05",
    source: "phone",
    type: "Architecture Photography",
    caption: "IMG_1834.jpeg",
    path: "/photos/mobile/Architecture%20Photography/IMG_1834.jpeg",
    tone: "rust",
  },
  {
    id: "p2-6",
    frame: "202P-06",
    source: "phone",
    type: "Architecture Photography",
    caption: "IMG_2257.JPG",
    path: "/photos/mobile/Architecture%20Photography/IMG_2257.JPG",
    tone: "graphite",
  },
  {
    id: "p2-7",
    frame: "202P-07",
    source: "phone",
    type: "Architecture Photography",
    caption: "IMG_2449.jpeg",
    path: "/photos/mobile/Architecture%20Photography/IMG_2449.jpeg",
    tone: "paper",
  },
  {
    id: "p2-8",
    frame: "202P-08",
    source: "phone",
    type: "Architecture Photography",
    caption: "IMG_2765.jpeg",
    path: "/photos/mobile/Architecture%20Photography/IMG_2765.jpeg",
    tone: "amber",
  },
  {
    id: "p2-9",
    frame: "202P-09",
    source: "phone",
    type: "Architecture Photography",
    caption: "IMG_4564.jpeg",
    path: "/photos/mobile/Architecture%20Photography/IMG_4564.jpeg",
    tone: "rust",
  },
  {
    id: "p2-10",
    frame: "202P-10",
    source: "phone",
    type: "Architecture Photography",
    caption: "IMG_4963.JPG",
    path: "/photos/mobile/Architecture%20Photography/IMG_4963.JPG",
    tone: "graphite",
  },
  {
    id: "p2-11",
    frame: "202P-11",
    source: "phone",
    type: "Architecture Photography",
    caption: "IMG_7456.JPG",
    path: "/photos/mobile/Architecture%20Photography/IMG_7456.JPG",
    tone: "paper",
  },
  {
    id: "p2-12",
    frame: "202P-12",
    source: "phone",
    type: "Architecture Photography",
    caption: "IMG_8227.JPG",
    path: "/photos/mobile/Architecture%20Photography/IMG_8227.JPG",
    tone: "amber",
  },
  {
    id: "p3-1",
    frame: "203P-01",
    source: "phone",
    type: "Landscape Photography",
    caption: "DJBB6081.JPG",
    path: "/photos/mobile/Landscape%20Photography/DJBB6081.JPG",
    tone: "rust",
  },
  {
    id: "p3-2",
    frame: "203P-02",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_0945.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_0945.JPG",
    tone: "graphite",
  },
  {
    id: "p3-3",
    frame: "203P-03",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_1020.jpeg",
    path: "/photos/mobile/Landscape%20Photography/IMG_1020.jpeg",
    tone: "paper",
  },
  {
    id: "p3-4",
    frame: "203P-04",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_1022.jpeg",
    path: "/photos/mobile/Landscape%20Photography/IMG_1022.jpeg",
    tone: "amber",
  },
  {
    id: "p3-5",
    frame: "203P-05",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_1221.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_1221.JPG",
    tone: "rust",
  },
  {
    id: "p3-6",
    frame: "203P-06",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_1613.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_1613.JPG",
    tone: "graphite",
  },
  {
    id: "p3-7",
    frame: "203P-07",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_1619.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_1619.JPG",
    tone: "paper",
  },
  {
    id: "p2-10",
    frame: "202P-10",
    source: "phone",
    type: "Architecture Photography",
    caption: "IMG_4963.JPG",
    path: "/photos/mobile/Architecture%20Photography/IMG_4963.JPG",
    tone: "graphite",
    featured: true,
  },
  {
    id: "p3-9",
    frame: "203P-09",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_1800.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_1800.JPG",
    tone: "rust",
  },
  {
    id: "p3-10",
    frame: "203P-10",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_1801.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_1801.JPG",
    tone: "graphite",
  },
  {
    id: "p3-11",
    frame: "203P-11",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_2278.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_2278.JPG",
    tone: "paper",
  },
  {
    id: "p3-12",
    frame: "203P-12",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_2313.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_2313.JPG",
    tone: "amber",
    featured: true,
  },
  {
    id: "p3-13",
    frame: "203P-13",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_2317.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_2317.JPG",
    tone: "rust",
  },
  {
    id: "p3-14",
    frame: "203P-14",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_2364.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_2364.JPG",
    tone: "graphite",
  },
  {
    id: "p3-15",
    frame: "203P-15",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_2365.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_2365.JPG",
    tone: "paper",
  },
  {
    id: "p3-16",
    frame: "203P-16",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_2437.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_2437.JPG",
    tone: "amber",
  },
  {
    id: "p3-17",
    frame: "203P-17",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_2571.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_2571.JPG",
    tone: "rust",
  },
  {
    id: "p3-18",
    frame: "203P-18",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_3172.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_3172.JPG",
    tone: "graphite",
  },
  {
    id: "p3-19",
    frame: "203P-19",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_3344.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_3344.JPG",
    tone: "paper",
  },
  {
    id: "p3-20",
    frame: "203P-20",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_3435.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_3435.JPG",
    tone: "amber",
  },
  {
    id: "p3-21",
    frame: "203P-21",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_3719.jpeg",
    path: "/photos/mobile/Landscape%20Photography/IMG_3719.jpeg",
    tone: "rust",
  },
  {
    id: "p3-22",
    frame: "203P-22",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_3720.jpeg",
    path: "/photos/mobile/Landscape%20Photography/IMG_3720.jpeg",
    tone: "graphite",
  },
  {
    id: "p3-23",
    frame: "203P-23",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_4520.jpeg",
    path: "/photos/mobile/Landscape%20Photography/IMG_4520.jpeg",
    tone: "paper",
  },
  {
    id: "p3-24",
    frame: "203P-24",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_5878.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_5878.JPG",
    tone: "amber",
  },
  {
    id: "p3-25",
    frame: "203P-25",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_5879.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_5879.JPG",
    tone: "rust",
  },
  {
    id: "p3-26",
    frame: "203P-26",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_5889.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_5889.JPG",
    tone: "graphite",
  },
  {
    id: "p3-27",
    frame: "203P-27",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_5890.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_5890.JPG",
    tone: "paper",
  },
  {
    id: "p3-28",
    frame: "203P-28",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_5958.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_5958.JPG",
    tone: "amber",
  },
  {
    id: "p3-29",
    frame: "203P-29",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_5959.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_5959.JPG",
    tone: "rust",
    featured: true,
    span: "wide",
  },
  {
    id: "p3-30",
    frame: "203P-30",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_7943.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_7943.JPG",
    tone: "graphite",
  },
  {
    id: "p3-31",
    frame: "203P-31",
    source: "phone",
    type: "Landscape Photography",
    caption: "IMG_E0969.JPG",
    path: "/photos/mobile/Landscape%20Photography/IMG_E0969.JPG",
    tone: "paper",
  },
  {
    id: "p3-32",
    frame: "203P-32",
    source: "phone",
    type: "Landscape Photography",
    caption: "JWCN6753.JPG",
    path: "/photos/mobile/Landscape%20Photography/JWCN6753.JPG",
    tone: "amber",
  },
  {
    id: "p4-1",
    frame: "204P-01",
    source: "phone",
    type: "Lifestyle Photography",
    caption: "IMG_1141.jpeg",
    path: "/photos/mobile/Lifestyle%20Photography/IMG_1141.jpeg",
    tone: "rust",
  },
  {
    id: "p4-2",
    frame: "204P-02",
    source: "phone",
    type: "Lifestyle Photography",
    caption: "IMG_1142.jpeg",
    path: "/photos/mobile/Lifestyle%20Photography/IMG_1142.jpeg",
    tone: "graphite",
  },
  {
    id: "p4-3",
    frame: "204P-03",
    source: "phone",
    type: "Lifestyle Photography",
    caption: "IMG_1908.JPG",
    path: "/photos/mobile/Lifestyle%20Photography/IMG_1908.JPG",
    tone: "paper",
    featured: true,
    span: "square",
  },
  {
    id: "p4-4",
    frame: "204P-04",
    source: "phone",
    type: "Lifestyle Photography",
    caption: "IMG_4040.JPG",
    path: "/photos/mobile/Lifestyle%20Photography/IMG_4040.JPG",
    tone: "amber",
  },
  {
    id: "p4-5",
    frame: "204P-05",
    source: "phone",
    type: "Lifestyle Photography",
    caption: "IMG_4897.JPG",
    path: "/photos/mobile/Lifestyle%20Photography/IMG_4897.JPG",
    tone: "rust",
  },
  {
    id: "p4-6",
    frame: "204P-06",
    source: "phone",
    type: "Lifestyle Photography",
    caption: "IMG_7258.JPG",
    path: "/photos/mobile/Lifestyle%20Photography/IMG_7258.JPG",
    tone: "graphite",
  },
];
